version: "3"
services: 
  springboot-app:
    container_name: springcontainer
    image: spring
    restart: always
    build: .
    ports:
      - 8080:8080 
      - 8081:8080
      - 8082:8080
      - 587:587
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqlcontainer
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306
    environment:
      MYSQL_DATABASE: cumulus
      MYSQL_ROOT_PASSWORD: 123456